apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: na-groupe12
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1 # Pour une base de donnée, ne pas mettre plus d'un réplica.
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: nicolas90/backend:a53bd45a
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: DB_HOST
                  name: backend-configmap
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  key: DB_PORT
                  name: backend-configmap
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: DB_NAME
                  name: backend-configmap
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  key: DB_USER
                  name: backend-configmap
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: DB_PASSWORD
                  name: backend-configmap
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: backend-configmap
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: backend-configmap
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: backend-configmap
          ports:
            - containerPort: 8000
